version: '3'
services:
  service-cloud-config:
    build: ./service-cloud-config
    ports:
      - "8888:8888"
    volumes:
        - configs:/tmp/config-repo
    environment:
        - GITHUB_TOKEN=${CONFIG_TOKEN}
    healthcheck:
        test: timeout 10s bash -c ':> /dev/tcp/service-cloud-config/8888' || exit 1
        interval: 10s
        retries: 5
  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/service-registry/8761' || exit 1
      interval: 10s
      retries: 5
  service-user:
    build: ./service-user
    ports:
      - "8001:8001"
      - "55001:55001"
    depends_on:
      service-registry:
        condition: service_healthy
      service-cloud-config:
        condition: service_healthy
      hackathon-hub-db:
        condition: service_started
    volumes:
      - ./service-user/build/libs/service-user-0.0.1-SNAPSHOT.jar:/app.jar
  service-auth:
    build: ./service-auth
    ports:
      - "8002:8002"
      - "55002:55002"
    depends_on:
      service-registry:
        condition: service_healthy
      service-cloud-config:
        condition: service_healthy
      hackathon-hub-db:
        condition: service_started
      tokens-redis:
        condition: service_started
    volumes:
      - ./service-auth/build/libs/service-auth-0.0.1-SNAPSHOT.jar:/app.jar
  service-team:
    build: ./service-team
    ports:
      - "8003:8003"
      - "55003:55003"
    depends_on:
      service-registry:
        condition: service_healthy
      service-cloud-config:
        condition: service_healthy
      hackathon-hub-db:
        condition: service_started
    volumes:
      - ./service-team/build/libs/service-team-0.0.1-SNAPSHOT.jar:/app.jar
  service-gateway:
    build: ./service-gateway
    ports:
      - "8082:8082"
      - "55004:55004"
    depends_on:
      service-registry:
        condition: service_healthy
      service-cloud-config:
        condition: service_healthy
      service-user:
        condition: service_started
      service-auth:
        condition: service_started
      service-team:
        condition: service_started
    volumes:
      - ./service-gateway/build/libs/service-gateway-0.0.1-SNAPSHOT.jar:/app.jar
  hackathon-hub-db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - hackathonhub_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hackathon-hub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  tokens-redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  configs:
    driver: local
  hackathonhub_db:
    driver: local
  cache:
    driver: local
