version: '3'
services:
  service-registry:
    build: ./service-registry
    ports:
      - 8761:8761
  users-database:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: usersControl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  tokens-database:
    image: postgres:12
    restart: always
    ports:
      - 5400:5432
    environment:
      POSTGRES_DB: tokensControl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  tokens-redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
