version: '3'
services:
  tokens-database:
    image: postgres:12
    restart: always
    ports:
      - 5400:5432
    environment:
      POSTGRES_DB: tokensControl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin