server:
  port: 0
spring:
  application:
    name: service-auth
  datasource:
    url: jdbc:postgresql://localhost:5400/tokensControl
    username: admin
    password: admin
  jdbc:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
grpc:
  server:
    port: 55002
  client:
    service-user:
      address: 'static://localhost:55001'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
jwt:
  secretKey: 0be2557f-8cdc-4fdb-b15b-c01a5813b9f6


logging:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE