version: '3'
services:
  users-database:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: usersControl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin